export const BROWSER_EXECUTION_RESERVATION_MS = 180_000;
export const BROWSER_OPERATOR_RESERVATION_MS = 300_000;
export const BROWSER_CONNECTION_RESERVATION_MS = 600_000;

export const BROWSER_EXECUTION_RESERVATION_MINUTES = BROWSER_EXECUTION_RESERVATION_MS / 60_000;
export const BROWSER_OPERATOR_RESERVATION_MINUTES = BROWSER_OPERATOR_RESERVATION_MS / 60_000;
